version: '3.7'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pokesmash

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - pokesmash

volumes:
  postgres_data:

networks:
  pokesmash: